### PR TITLE
Docker build automation

### PR DESCRIPTION
**Pull request by jay-dee7**
* split docker image into base and main

### CODE REVIEW

**Comment by jay-dee7** [comment]
Hey @inspiraluna maybe you'd want to revert this. The docker image referred in main Dockerfile is coming from my account, maybe you'd want to host it under doichain's dockerhub account and then refer it from there?

**Comment by inspiraluna** [comment]
lets see if this works.  Long time ago I already had a base docker image. Not sure why it suddenly disappeared. It's still building the first version. Lets see.

**Comment by jay-dee7** [comment]
sure, it'll take around 40ish minutes i guess for the base image and then around 50  minutes for the main image

**Comment by jay-dee7** [comment]
@inspiraluna looks like the build was successful?

**Comment by inspiraluna** [comment]
looks very good! we should change the base image now.

**Comment by jay-dee7** [comment]
> looks very good! we should change the base image now.

That's something you'll have to do i guess. just point to the `base.Dockerfile` and add another build on docker hub, if you comment the name for the base docker image, i'll raise another pr with name changes.

**Pull request merged**
